### ISSUE TITLE
I can not perform query using order by

### ISSUE THREAD

**Issue by javidep** [talent-path-la/postie#5]
I all,

I am trying yo perform query using order by, the query does not return data. 

This is my query, what is wrong? please help!

Firestore.instance.collection("users")
          .orderBy("numberHits", descending: false)
          .limit(1)
          .snapshots()
          .listen((data) =>
          data.documents.forEach((doc) => userName = (doc["name"])));

PS: I just created index for numberHits in Firestore using firebase console.

Thanks and regards,

Javier

**Comment by AbleLincoln** [comment]
I'm sorry, but this repository isn't for Firebase questions. This is just a project I created to teach a class. I would recommend trying StackOverflow.

Best of luck!
